"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 10:12:42.740401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broadcast', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kasa_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kasa_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('miio_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('miio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tuya_device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tuya_local_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tuya_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hw_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hw_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hw_is_strip', sa.Boolean(), nullable=False),
    sa.Column('last_known_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_mac'), ['mac'], unique=True)

    op.create_table('outlet',
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outlet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'outlet_id')
    )
    op.create_table('outlet_token',
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outlet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'outlet_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlet_token')
    op.drop_table('outlet')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_mac'))

    op.drop_table('device')
    # ### end Alembic commands ###
